version: "3.8"

services:
  frontend:
    image: afrazdev/cowlar:frontend-image
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    container_name: cowlar_cont_frontend

  backend:
    image: afrazdev/cowlar:backend-image
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    container_name: cowlar_cont_backend
